# Generated by Django 3.1.12 on 2025-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
