# Generated by Django 3.1.12 on 2025-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
