# Generated by Django 3.1.12 on 2025-08-13 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arsip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDateTime', models.DateTimeField(auto_now=True)),
                ('nota_receipt_id', models.CharField(blank=True, max_length=10, null=True)),
                ('nota_cust_name', models.CharField(max_length=100)),
                ('nota_date', models.DateField()),
                ('nota_image_file', models.ImageField(blank=True, null=True, upload_to='nota_image_file')),
                ('nota_notes', models.TextField(blank=True, max_length=400, null=True)),
                ('ganti_nota', models.BooleanField(default=False)),
                ('nota_sudah_diambil', models.BooleanField(default=False)),
                ('nota_sudah_diambil_dateTime', models.DateTimeField(blank=True, null=True)),
                ('nota_previous_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_id', to='arsip.arsip')),
                ('nota_sudah_diambil_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('userUploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userUploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
