# Generated by Django 3.1.12 on 2025-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsip',
            name='nota_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='nota_image_file/'),
        ),
    ]
