# Generated by Django 3.1.12 on 2025-09-17 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arsip', '0002_auto_20250813_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsip',
            options={'ordering': ['nota_date']},
        ),
        migrations.AddField(
            model_name='arsip',
            name='nota_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Request Tarik Nota'), ('approved', 'Approved'), ('rejected', 'Di-Reject'), ('taken', 'Sudah Diambil/Selesai')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ArsipLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pending', 'Pending'), ('status_change', 'Ubah Status'), ('update', 'Diupdate'), ('delete', 'Hapus')], max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('arsip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='arsip.arsip')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
