# Generated by Django 3.1.12 on 2025-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0003_auto_20250917_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsip',
            name='nota_pic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
