# Generated by Django 3.1.12 on 2025-09-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0004_arsip_nota_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsip',
            name='uploadDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
