# Generated by Django 3.1.12 on 2025-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0005_auto_20250923_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsip',
            name='nota_status',
            field=models.CharField(choices=[('unposted', 'Belum Diposting'), ('req_tarik_nota', 'Request Posting: Tarik Nota'), ('req_ganti_nota', 'Request Posting: Ganti Nota'), ('req_retur_nota', 'Request Posting: Retur Nota'), ('posted', 'Sudah Diposting')], default='unposted', max_length=20),
        ),
    ]
